### ISSUE TITLE
Embed 'monobit'?

### ISSUE THREAD

**Issue by trevorld** [coolbutuseless/bdftools#1]
[monobit](https://github.com/robhagemans/monobit) is a MIT-licensed Python library that can convert to/from many bitmap fonts.  If embedded and assuming the user has Python installed then you could easily extend read/write support to most bitmap font formats instead of just BDF.  Could make such a Python dependency a "Suggested" dependency (instead of hard requirement).

**Comment by trevorld** [comment]
After playing around with converting files with `monobit` I'm not sure its `bdf` support is ready.

**Comment by coolbutuseless** [comment]
I've found that 99% of the bitmap fonts I want are in bdf. A separate conversion library could be interesting, but I don't have a motivating use case just yet
