### ISSUE TITLE
Support "block element" "compression" in 'bdf_print_sample()'?

### ISSUE THREAD

**Issue by trevorld** [coolbutuseless/bdftools#3]
* [Block elements](https://en.wikipedia.org/wiki/Block_Elements) could be used to reduce "pixels" in plaintext representation by 2/4 times assuming user's font supports the "Block Elements" block allowing more characters to be viewed at in the terminal.  Many bitmap fonts have even heights (and widths) but if they do not then would need to introduce a bit of whitespace at bottom/right...
* Just using "upper/lower/full" block could reduce vertical height of text by 2 times.  If user is using a font with close to a 1:2 aspect ratio then this would also lead to a more "realistic" rendering...
* Also using the various "quadrant" characters could reduce both vertical and horizontal lengths by 2 (reduces total "pixels" by four).  A "realistic" rendering if user is using a font with close to 1:1 aspect ratio...

**Comment by coolbutuseless** [comment]
```
  ██▄      ▄██                                    ██                                   ██
  ████▄  ▄████                                    ██                                   ██
  ██ ▀████▀ ██                                    ██                                   ██
  ██   ▀▀   ██     █████████▄     ██        ██    ██████████▄      ▄██████████         ██
  ██        ██             ▀██    ██        ██    ██       ▀██    ██▀       ██         ██
  ██        ██      ▄▄▄▄▄▄▄▄██    ██        ██    ██        ██    ██        ██         ██
  ██        ██    ▄██▀▀▀▀▀▀▀██    ██        ██    ██        ██    ████████████         ██
  ██        ██    ██        ██    ██        ██    ██        ██    ██                     
  ██        ██    ██▄       ██    ██▄       ██    ██       ▄██    ██▄                  ▄▄
  ██        ██     ▀██████████     ▀██████████    ██████████▀      ▀██████████         ██
                                            ██                                           
                                           ▄██                                           
                                  ██████████▀                                            
```

**Comment by trevorld** [comment]
It's a shame there isn't an easy way to adjust the CSS line-height style within Github.  Looks great in the terminal!
